'use client';

import { useTranslations } from 'next-intl';

export default function Disclaimer() {
  const t = useTranslations();
  
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-3xl font-bold mb-8 text-primary">
        {t('footer.disclaimer')}
      </h1>
      
      <div className="prose prose-lg max-w-none">
        <h2>No Liability</h2>
        <p>
          The passwords generated by Top Password Generator are provided "as is" without warranty of any kind. 
          While we strive to create secure and reliable passwords, we cannot guarantee their absolute security 
          against all possible attacks or vulnerabilities.
        </p>
        
        <h2>No Storage</h2>
        <p>
          We do not store, log, or have access to any passwords generated by our service. All password generation 
          occurs entirely in your browser. However, we cannot be responsible for how you store or use these passwords 
          after generation.
        </p>
        
        <h2>Use at Your Own Risk</h2>
        <p>
          You acknowledge and agree that your use of this password generator is at your own risk. We recommend using 
          generated passwords in conjunction with other security measures such as two-factor authentication where available.
        </p>
        
        <h2>Third-Party Services</h2>
        <p>
          If you use our generated passwords with third-party services or websites, those services' own security 
          measures will affect the security of your accounts. We have no control over and assume no responsibility 
          for the security practices of any third-party services.
        </p>
        
        <h2>No Professional Advice</h2>
        <p>
          The information provided on this website regarding password security is for general informational purposes 
          only and should not be construed as professional security advice. For specific security requirements, 
          please consult with a qualified cybersecurity professional.
        </p>
        
        <p className="text-sm text-gray-500 mt-8">
          Last updated: March 10, 2025
        </p>
      </div>
    </div>
  );
}
