import { Metadata } from 'next';
import LegalPageWrapper from '@/components/legal-page-wrapper';

export const metadata: Metadata = {
  title: 'Disclaimer - Top Password Generator',
};

export default function Disclaimer() {
  return (
    <LegalPageWrapper titleKey="footer.disclaimer">
      {(t) => (
        <>
          <h2>Password Security Disclaimer</h2>
          <p>
            Top Password Generator provides tools to help you create strong passwords. However, we cannot guarantee 
            absolute security. The security of your passwords depends on many factors beyond our control, including 
            how you store and use them.
          </p>
          
          <h2>No Storage of Passwords</h2>
          <p>
            We do not store, log, or have access to any passwords you generate using our service. All password 
            generation occurs entirely within your browser.
          </p>
          
          <h2>QR Code Security</h2>
          <p>
            When using our QR code feature, please be aware that anyone who scans the QR code may be able to access 
            the encoded password. Use the encryption and expiration features for sensitive passwords, and share QR codes 
            only through secure channels.
          </p>
          
          <h2>Password Strength</h2>
          <p>
            While we provide tools to generate strong passwords, the actual strength of a password depends on various 
            factors, including length, complexity, and randomness. We recommend using the longest, most complex passwords 
            that are practical for your specific use case.
          </p>
          
          <h2>No Liability</h2>
          <p>
            We are not liable for any security breaches, data loss, or other damages that may result from using passwords 
            generated by our service. You are solely responsible for maintaining the security of your accounts and passwords.
          </p>
          
          <h2>Third-Party Services</h2>
          <p>
            If you choose to check if a password has been breached using our service, this check is performed using 
            third-party services. While we take precautions to protect your privacy during this process, we cannot 
            guarantee the security or privacy practices of these third-party services.
          </p>
          
          <p className="text-sm text-gray-500 mt-8">
            Last updated: March 10, 2025
          </p>
        </>
      )}
    </LegalPageWrapper>
  );
}
