export default function Disclaimer() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-3xl font-bold mb-8 text-primary text-center">
        Disclaimer
      </h1>
      
      <div className="prose prose-lg max-w-none bg-white p-8 rounded-lg shadow-sm">
        <h2 className="text-2xl font-semibold text-gray-800 border-b pb-2 mb-4">No Liability</h2>
        <p className="text-gray-700 mb-6">
          The passwords generated by Top Password Generator are provided "as is" without warranty of any kind. 
          While we strive to create secure and reliable passwords, we cannot guarantee their absolute security 
          against all possible attacks or vulnerabilities.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 border-b pb-2 mb-4">No Storage</h2>
        <p className="text-gray-700 mb-6">
          We do not store, log, or have access to any passwords generated by our service. All password generation 
          occurs entirely in your browser. However, we cannot be responsible for how you store or use these passwords 
          after generation.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 border-b pb-2 mb-4">Use at Your Own Risk</h2>
        <p className="text-gray-700 mb-6">
          You acknowledge and agree that your use of this password generator is at your own risk. We recommend using 
          generated passwords in conjunction with other security measures such as two-factor authentication where available.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 border-b pb-2 mb-4">Third-Party Services</h2>
        <p className="text-gray-700 mb-6">
          If you use our generated passwords with third-party services or websites, those services' own security 
          measures will affect the security of your accounts. We have no control over and assume no responsibility 
          for the security practices of any third-party services.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 border-b pb-2 mb-4">No Professional Advice</h2>
        <p className="text-gray-700 mb-6">
          The information provided on this website regarding password security is for general informational purposes 
          only and should not be construed as professional security advice. For specific security requirements, 
          please consult with a qualified cybersecurity professional.
        </p>
        
        <p className="text-sm text-gray-500 mt-10 pt-4 border-t">
          Last updated: March 10, 2025
        </p>
      </div>
    </div>
  );
}
